//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonesEmpresariales
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public int ID_cliente { get; set; }
        public string Nombre_cliente { get; set; }
        public string Apellido_cliente { get; set; }
        public string Telefono_cliente { get; set; }
        public string Correo_cliente { get; set; }
        public Nullable<long> Edad_cliente { get; set; }
        public Nullable<long> Identificacion_cliente { get; set; }
        public Nullable<bool> Borrado { get; set; }
        public Nullable<int> Departamento { get; set; }
        public string Municipio { get; set; }
    }
}
