//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonesEmpresariales
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventos
    {
        public int ID_evento { get; set; }
        public Nullable<int> Cliente_id { get; set; }
        public string fecha_Evento { get; set; }
        public Nullable<int> Cantidad_personas { get; set; }
        public string Motivo { get; set; }
        public string observaciones { get; set; }
        public string estado { get; set; }
        public Nullable<bool> Borrar { get; set; }
    }
}
