//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonesEmpresariales
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipios
    {
        public int ID_municipio { get; set; }
        public long departamento_id { get; set; }
        public int codigo { get; set; }
        public string nombre { get; set; }
    }
}
