//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonesEmpresariales
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SalonesEmpresarialesXYZEntities : DbContext
    {
        public SalonesEmpresarialesXYZEntities()
            : base("name=SalonesEmpresarialesXYZEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<departamentos> departamentos { get; set; }
        public virtual DbSet<municipios> municipios { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<Motivo_Estado> Motivo_Estado { get; set; }
        public virtual DbSet<eventos> eventos { get; set; }
    
        public virtual ObjectResult<pa_Reporte_Result> pa_Reporte()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Reporte_Result>("pa_Reporte");
        }
    }
}
